apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-statefulset
  namespace: argocd
spec:
  project: default
  source:
    path: app/
    repoURL: 'https://github.com/christianh814/testing'
    targetRevision: main
  destination:
    name: in-cluster
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
